[package]
name = "ppt2"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
solana-program = "1.14.15" 
borsh = "0.10.3"
borsh-derive = "0.10.3"
anchor-lang = "0.31.1"

[features]
idl-build = ["anchor-lang/idl-build"]